name: Build

# Run this workflow every time a new commit pushed to your repository

on: push

env:
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  linux:
    name: Build Linux x86-64 code and wrapper
    runs-on: ubuntu-22.04
    steps:
      - name: Ubuntu packages
        run: sudo apt-get install -y libeatmydata1
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Build native library
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./native/build-linux.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            *.so
